language: node_js
node_js:
  - "6.9"
branches:
  only:
    - develop
    - master
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g bower
  - npm install -g webpack
  - npm install -g typescript
  - npm install -g mocha
  - npm install -g karma
  - npm install -g karma-chrome-launcher
  - npm install -g karma-mocha
  - npm install -g chai
  - npm build:prod
  - npm test
